import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const html = await readFile(new URL('./index.html', import.meta.url), 'utf8');
const cardStart = html.indexOf('<h2>Recent timestamped product activity</h2>');
const cardEnd = html.indexOf('</section>', cardStart);
assert.notEqual(cardStart, -1, 'activity card exists');
assert.notEqual(cardEnd, -1, 'activity card has a section boundary');
const card = html.slice(cardStart, cardEnd);
const region = card.match(/<div id="recent-events"([^>]*)>/)?.[1];
assert.ok(region, 'existing activity wrapper remains the scroll region');
assert.match(region, /role="region"/);
assert.match(region, /aria-label="Recent timestamped product activity"/);
assert.match(region, /tabindex="0"/, 'region can receive keyboard focus');

const scrollStyle = html.match(/#recent-events\s*\{([^}]*)\}/)?.[1];
assert.ok(scrollStyle, 'activity wrapper has dedicated bounded scrolling styles');
assert.match(scrollStyle, /max-height\s*:\s*24rem/);
assert.match(scrollStyle, /overflow-x\s*:\s*auto/);
assert.match(scrollStyle, /overflow-y\s*:\s*hidden/);
assert.match(scrollStyle, /scrollbar-color/);
assert.match(html, /#recent-events::-webkit-scrollbar-thumb\s*\{[^}]*background\s*:\s*var\(--cyan\)/);
const tableStyle = html.match(/#recent-events table\s*\{([^}]*)\}/)?.[1];
assert.ok(tableStyle, 'activity table has an isolated border model for consistent header/row layout');
assert.match(tableStyle, /border-collapse\s*:\s*separate/);
assert.match(tableStyle, /border-spacing\s*:\s*0/);
const bodyStyle = html.match(/#recent-events tbody\s*\{([^}]*)\}/)?.[1];
assert.ok(bodyStyle, 'activity rows have their own scroll viewport below the headings');
assert.match(bodyStyle, /display\s*:\s*block/);
assert.match(bodyStyle, /max-height\s*:\s*20rem/);
assert.match(bodyStyle, /overflow-y\s*:\s*auto/);
assert.match(bodyStyle, /overscroll-behavior\s*:\s*contain/);
assert.match(bodyStyle, /scrollbar-color/);
assert.match(html, /#recent-events tbody::-webkit-scrollbar-thumb\s*\{[^}]*background\s*:\s*var\(--cyan\)/);
const headerStyle = html.match(/#recent-events thead th\s*\{([^}]*)\}/)?.[1];
assert.ok(headerStyle, 'activity headings retain normal table flow');
assert.doesNotMatch(headerStyle, /position\s*:\s*sticky/);
assert.match(html, /#recent-events thead,\s*#recent-events tbody tr\s*\{[^}]*display\s*:\s*table/);

const rendererStart = html.indexOf('  function renderEvents(items) {');
const rendererEnd = html.indexOf('\n  function renderAnswerDisplayTimings', rendererStart);
assert.notEqual(rendererStart, -1, 'activity renderer exists');
assert.notEqual(rendererEnd, -1, 'activity renderer boundary exists');
const renderer = html.slice(rendererStart, rendererEnd);
assert.match(renderer, /target\.innerHTML\s*=\s*'<table><thead>/, 'existing table/header rendering is preserved');
assert.match(renderer, /<tbody tabindex="0" aria-label="Scrollable product activity rows">/);
assert.match(renderer, /items\.map\(\(event\)/, 'all supplied rows remain rendered in their existing order');
assert.match(renderer, /localTimestamp\(event\.occurred_at\)/, 'existing timestamp binding remains intact');

console.log('activity scroll region checks passed');
